### ISSUE TITLE
Missing bibliographic references in the source code

### ISSUE THREAD

**Issue by asr** [acalles1/setform#3]
Please added the references for your axioms and theorems.

**Comment by acallesalda** [comment]
Fixed with latest commit.

**Comment by asr** [comment]
> Fixed with latest commit.

Which is the commit SHA?

**Comment by acallesalda** [comment]
It was this commit I was refering to:

https://github.com/acalles1/setform/commit/a30099dafc85318f6355f4e8f38865fe24cd5338

But I uploaded in the wrong directory. In this comit I correct my error:

https://github.com/acalles1/setform/commit/84f6e86551b44ff6034c3dc7f9c792746951eab8

So now they references are in the SetTheory.agda file in the src directory.
