### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by asr** [acalles1/setform#4]
If you prove says Suppes' Theorem 43, please added this information to the source code.

**Comment by asr** [comment]
Did you fix the issue?

**Comment by acallesalda** [comment]
Yes, fixed it a long time ago. I believe all theorems proved have the corresponding bibliographic remark (in the line before their statement, or if they don't have the bibliographic remark then they were not in any book I was consulting). I guess I forgot to close the issue back then. Was just reviewing old code and wanted to close all issues.
